/**
 * This class contains the constant values which uses to show
 * default text content or hint/placeholder for the components.
 */
export default {
  SIGN_UP: 'Sign Up',
  LOGIN: 'Log In',
  CONTINUE_BUTTON: 'Continue',
  BACK_BUTTON: 'Back',
  EMAIL: 'Email ',
  PASSWORD: 'Password',
  FORGOT: 'Forgot ',
  OR: 'Or ',
  FA_ENABLED: '2FA (If Enabled)',
  WHAT_IS: 'What is ',
  TWO_WAY_AUTHENTICATION: 'Two-Factor Authenticator',
  DONT_HAVE_ACCOUNT: "Don't Have An Account? ",
  BUY_SEND_AND_EXCHANGE_FIAT_CURRENCY_WITH_CRYPTO:
    'Buy, Send And Exchange \nFiat Currency With \nCryptocurrency',
  MERCURY_DOT: 'mercury.',
  CASH: 'cash',
  QUESTION_MARK: '?',
  CONFIRM_PASSWORD: 'Confirm Your Password',
  WHERE_IS_YOUR_RESIDENCY: 'Where Is Your Primary Residence?',
  RESIDENCE: 'Residence',
  BY_CONTINUING_I_AGREE: 'By Continuing I Agree To The ',
  TERMS_OF_SERVICES: 'Terms Of \n Services',
  AND_SPACE: ' And ',
  PRIVACY_POLICY: 'Privacy Policy',
  ALREADY_CREATED_ACC: 'Already Created An Account?',
  SIGN_IN_SLASH: '\nSign In ',
  INSTEAD: 'Instead.',
  PASSWORD_CHARS_LIMIT: '8 Characters',
  PASSWORD_UPPER_LIMIT: '1 Uppercase',
  PASSWORD_LOWER_LIMIT: '1 Lowercase',
  PASSWORD_DIGIT_LIMIT: '1 Digit',
  PASSWORD_SPECIAL_CHAR_LIMIT: '1 Special Character',
  TERMS_AND_CONDITIONS: 'Terms & conditions',
  CANCEL: 'Cancel',
  WELCOME_DASHBOARD: 'Welcome Dashboard',
  YOUR_PASS_WORD_MUST_CONTAIN: 'Your password must contain:',
  TERMS_TEXT:
    'Last updated: May 7, 2018\n\n Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.\n\n' +
    'There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which dont look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there is not anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.\n\n' +
    'It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using content here, content here, making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for lorem ipsum will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose',
  BACK: 'Back',
  THANKS_FOR_REGISTERING: 'Thanks for\n Registering!',
  THANKS_CONTENT: 'Thank you for registering. We have sent\nyou an email to verify your account',
  OPEN: 'Open ',
  MAIL_APP: 'Your Mail App',
  HEADER_MERCURY: 'mercury.',
  ONBOARDING_PROCESS: 'Onboarding Process',
  SIGNUP_PROGRESS_TITLE: 'Finish Setting Up Your\nMercury Cash Account',
  VERIFY_YOUR_IDENTITY: 'Verify Your Identity',
  SECURE_YOUR_ACCOUNT: 'Secure Your Account',
  ADD_BANK_ACCOUNT: 'Add A Bank Account',
  VERIFY_IDENTITY_DESC: 'Get Verified To Start\nBuying And Selling\nCryptocurrency',
  SECURE_ACCOUNT_DESC:
    'Login 2FA Keeps Your Account\nSecure By Adding Aditional\nAuthentication Method',
  ADD_BANK_ACCOUNT_DESC:
    'Add A Bank Account To Fund\nYour USD Wallet And Make\nYour First Prychase',
  SELECT_ACCOUNT_TYPE: 'Select Account Type',
  SELECT_ACCOUNT_TYPE_DESC: 'Select the type of Account\nyou want to have ',
  PERSONAL: 'Personal',
  BUSINESS: 'Business',
  PERSONAL_INFORMATION: 'Personal Information',
  PERSONAL_INFO_DESC: 'Please Enter Your Personal Information',
  FIRST_NAME: 'First Name',
  LAST_NAME: 'Last Name',
  DATE_OF_BIRTH: 'Date Of Birth',
  NATIONALITY: 'Nationality',
  PHONE_VERIFICATION: 'Phone Verification',
  PLEASE_ENTER_PHONE_NUMNER: 'Please Enter Your Phone Number',
  PHONE_NUMBER: 'Phone Number',
  GENDER: 'Gender',
  ADDRESS_INFORMATION: 'Address information',
  ADDRESS_INFO_DESC: 'Please fill your address information ',
  ADDRESSLINE_ONE: 'Address Line 1',
  ADDRESSLINE_TWO: 'Address Line 2 (Optional)',
  COUNTRY: 'Country',
  STATE: 'State',
  CITY: 'City',
  ZIP_CODE: 'Zip Code',
  DOCUMENT_HASS: 'Document #',
  OCUPATION: 'Ocupation',
  PROFESSION: 'Profession',
  TAX_ID: 'TAX ID / EIN',
  CATEGORY: 'Category',
  ALERT: 'Alert',
  OK: 'Ok',
  CHANGE: 'Change',
  ENTER_CODE: 'Enter the 6 digit and 1 letter code\nsent To your mobile number',
  HYPHEN: '-',
  DID_NOT_GET_CODE: 'Didn’t get your code?,',
  CLICK_HERE: ' Click here',
  TO_SEND_CODE: 'to\nsend a new one',
  VERIFIED_TEXT: 'Your Phone Number\nhas been Verified Succesfully',
  DOCUMENT_TYPE: 'Document Type',
  SELECT_DOCUMENT: 'Select a Document, you will take\na picure of it in the next step',
  PASSPORT: 'International Passport',
  LICENSE: 'Driver’s License',
  ID_CARD: 'Identification Card',
  DASHBOARD: 'dashboard',
  TWO_WAY_TITLE: 'Don’t forget to secure your\naccount with two factor\nauthentication',
  TWO_WAY_CONTENT:
    'your account security is our highest priority. for this reason we now require you to set up and use login two-factor authantication (2FA)',
  SECURE_ACCOUNT: 'Secure Account',
  BUSINESS_INFORMATION: 'Bussiness Information',
  BUSINESS_INFO_DESC: 'Please Enter The Information\nAbout Your Company',
  COMPANY_NAME: 'Company Name',
  ADDRESS: 'Address',
  TOTAL_HOLDINGS: 'Total Holdings (In USD)',
  TYPE_ALL: 'ALL',
  TYPE_BITCOIN: 'BITCOIN',
  TYPE_DASH: 'DASH',
  TYPE_USD: 'USD',
  TYPE_ETH: 'ETH',
  TYPE_EURO: 'EURO',
  TYPE_BTC: 'BTC',
  VALUE_EURO: 'EUR',
  BITCOIN_BALANCE: 'Bitcoin Balance',
  DASH_BALANCE: 'Dash Balance',
  ETHEREUM_BALANCE: 'Ethereum Balance',
  USD_BALANCE: 'USD Balance',
  EURO_BALANCE: 'Euro Balance',
  PLATFORM_ANDROID: 'android',
  UPLOAD_DOCUMENTS: 'Upload Documents',
  UPLOAD_DOCUMENT_DESC: 'We Need A Few Documents Of Your Company\nTo Verify Your Business Account',
  ETHERIUM: 'Ethereum',
  DOLLAR: 'USD',
  BITCOIN: 'Bitcoin',
  DASH: 'Dash',
  RECENT_TRANSACTIONS: 'Your Recent Transactions',
  ALL: 'ALL',
  SENT: 'SENT',
  RECEIVED: 'RECEIVED',
  BOUGHT: 'BOUGHT',
  SOLD: 'SOLD',
  BUY_SMALL: 'buy',
  SOLD_SMALL: 'sold',
  SELL_SMALL: 'sell',
  RECEIVED_SMALL: 'received',
  SENT_SMALL: 'sent',
  TYPE_OF_DOCUMENT: 'Type of Identity Document',
  DOCUMENT_NUMBER: 'Document Number',
  TYPE: 'Type:',
  FROM: 'from:',
  TO: 'To:',
  RATE: 'Rate:',
  AMOUNT: 'Amount:',
  VALUE: 'Value:',
  DATE: 'Date:',
  COMMENT: 'Comment:',
  HASH: 'hash:',
  SEND: 'SEND',
  SAVE_PDF: 'SAVE (PDF) ',
  NAME_TAG: '"nametag" - ',
  RECORD: 'record ',
  CURRENT_VALUE: 'current value:',
  I_WANT_TO_SEND: 'I want to send:',
  EURO: 'Euro',
  ERROR: 'Error',
  SMS_AUTHENTICATION: 'SMS Authentication',
  TFA_AUTHENTICATION: '2FA Authentication',
  SEND_TFA_INFO: 'Enter 6 digit code from your\n2FA Application in your Phone',
  SEND_SMS_INFO: 'a 6 digit code has been sent to\n',
  OTP_DUMMY_TEXT: '***-***',
  VIA_SMS: ' via SMS ',
  OTP_EXPIRES_IN: 'The OTP will expire in ',
  OTP_EXPIRES_TIME: '5:59',
  BULLET_UNICODE: '\u2022 ',
  OTP_RESEND_TEXT: 'Didn’t receive the code? ',
  IT: ' it.',
  RESEND: 'Resend',
  SEND_SMALL: 'Send:',
  AVAILABLE: 'Available in your',
  WALLET: 'Wallet',
  USED_LIMIT: 'Used\nLimit',
  SEND_EVERYTHING: 'Send Everything',
  AMOUNT_OF: 'THE AMOUNT OF:',
  USD_TRANSFER: 'usd_transfer',
  USD_SYMBOL: '$',
  EURO_SYMBOL: '€',
  SEND_TO: 'Send:',
  MY_BANK_ACCOUNT: 'My Bank Account',
  A_CONTACT: 'A Contact',
  YOU_TRANSFER: "You'll Transfer:",
  FEE: 'Fee:',
  YOU_GET: "You'll Get:",
  USD_WALLET: 'USD Wallet',
  EURO_WALLET: 'EUR Wallet',
  VERIFY: 'Verify',
  SMS_VERIFY_SUCCESS: 'Your SMS Code has been\nVerified succesfully',
  TFA_VERIFY_SUCCESS: 'Your 2FA  has been\nVerified succesfully',
  SMS: 'sms',
  TFA: '2fa',
  BANK_ACCOUNT_NAME: 'Bank Account Name',
  ADD_NEW_BANK_ACCOUNT: 'Or Add new Bank account',
  SUCCESS_CAPS: 'SUCCESS!',
  YOU_SENT: 'You Sent:',
  YOU_GOT: 'You Got:',
  TRANSACTION: 'transaction',
  IN_PROGRESS: 'in progress',
  TRANSFER: 'Transfer',
  PLEASE_SELECT_BANK: 'Please select Bank and proceed..',
  CURRENCY: 'Currency',
  NAME: 'Name:',
  NAME_PLACEHOLDER: 'name',
  E_MAIL: 'e-mail:',
  ADDRESS_COLON: 'Address:',
  SCAN_QR_CODE: 'Scan QR Code Instead',
  ADD_NEW_CONTACT: 'Add New Contact',
  CONTACT_ADDED: 'Contact Added!',
  SEND_MONEY: 'Send Money',
  WITHDRAW: 'Withdraw',
  SEARCH: 'Search',
  ENGLISH_US: 'en-US',
  WITHDRAW_SMALL: 'withdraw',
  TYPE_CONTACT: 'Contact',
  TYPE_BANK_ACCOUNT: 'Bank Account',
  TOTAL_PAID: 'Total Paid:',
  PAYING_INVOICE: 'Are you paying an invoice?\n(Business Transaction)',
  YES: 'Yes',
  NO: 'No',
  UPLOAD_INVOICE: 'Upload an invoice',
  REASON_FOR_TRANSACTION: 'Please describe the reason of this transaction...',
  TFA_CAPS: 'TFA',
  SMS_CAPS: 'SMS',
  TYPE_SEND: 'SEND',
  TYPE_DEPOSIT: 'DEPOSIT',
  I_WANT_TO_DEPOSIT: 'I want to deposit:',
  DEPOSIT: 'Deposit ',
  OUTSIDE_MERCURY_CASH: 'Outside Mercury Cash',
  REQUEST_TO_CONTACT: 'Request To Contact',
  CONTACT: 'Contact',
  OUTSIDE_MERCURY: 'Outside Mercury',
  SEGWIT_ADDRESS: 'Your Segwit Addresses',
  LEGASY_ADDRESS: 'Your Legacy Addresses',
  DEPOSIT_QR_TEXT:
    'copy and paste the wallet\naddress or use the QR\ncode to show the sender\nyour address',
  VIEW_QR_CODE: 'View QR CODE ',
  COPY_ADDRESS: 'Copy Address',
  QR_CODE_LOGO_PATH: require('App/Assets/Images/Png/logo.png'),
  ADDRESS_NAME_BITCOIN: 'bitcoin:',
  ENTER_EMAIL: 'enter e-mail',
  ENTER_DESCRIPTION: 'enter description',
  THE_AMOUNT_OF: 'THE AMOUNT OF:',
  AVAILABLE_IN_YOUR_USD_WALLET: ' Available in your USD Wallet',
  DUMMY_AMOUNT: 0,
  SEND_EMAIL: 'Send E-mail',
  PLEASE_ADD_CONTACT: 'Please Add contact and try again',
  DONE: 'Done',
  ETHERIUM_COLON: 'ethereum:',
  BITCOIN_COLON: 'bitcoin:',
  DASH_COLON: 'dash:',
  ADDRESS_PLACEHOLDER: 'Paste or write the address here..',
  SCAN: 'SCAN',
  USE_LIGHTING_NETWORK: 'Use Lighting Network',
  RATE_FOR_THIS_TRANSACTION: 'Rate For This Transaction',
  SAVE_ADDRESS_AS_CONTACT: 'Save address as a contact?',
  WALLET_NAME: 'WALLET NAME',
  BALANCE: 'BALANCE',
  ADDRESS_NAME_ETHEREUM: 'ethereum:',
  ADDRESS_NAME_DASH: 'dash:',
  RECEIPENT_GETS: 'Receipent Get',
  TRANSFER_USD: 'transfer/usd',
  INSTANT_SEND: 'Use InstantSend',
  IDENTIFY_CONTACT_WITH_EMAIL:
    'Would you like to identify this contact with an email address? (Optional)',
  YOUR_SEND_LIMITS: 'Your Send Limits',
  YOUR_LIMIT: 'YOUR LIMIT',
  USED: 'USED',
  LEFT: 'LEFT',
  VIEW_ALL_MY_LIMITS: 'View all My limits',
  LIGHTNING_HINT:
    'We are working hard to implement Lightning Network, after our 2.0 release we will focus on features like this to be released in future versions, we invite you to keep posted in our official channels',
  PROFILE: 'Profile',
  DOCUMENTS: 'Documents',
  BANK_ACCOUNTS: 'Bank Accounts',
  SECURITY: 'Security',
  LIMITS: 'Limits',
  REGIONAL_SETTINGS: 'Regional Settings',
  LOGOUT: 'Log Out',
  BANK: 'Bank:\n',
  BANK_TYPE: 'Type:\n',
  ALIAS: 'Alias:\n',
  STATUS: 'Status:',
  ADD_NEW_BANK_ACCOUNTS: 'ADD NEW\nBANK\nACCOUNT',
  DOMESTIC: 'Domestic',
  INTERNATIONAL: 'International',
  VERIFIED: 'VERIFIED',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  ADD_AGAIN: 'ADD AGAIN',
  BANK_SEND_EMAIL: 'SEND E-MAIL',
  NOTIFICATIONS: 'Notifications',
  ON: 'On',
  OFF: 'Off',
  BACK_TO_DASHBOARD: 'Back To Dashboard',
  LOG_OUT: 'LOG_OUT',
  ADD_NEW_BANK_ACCOUNT_TITLE: 'Add New Bank Account',
  USA_BANK_ACCOUNT: 'USA (Swift Bank account)',
  EURO_BANK_ACCOUNT: 'EU/EEA ( SEPA Bank Account)',
  USA_SWIFT: 'USA/SWIFT',
  BENEFICIARY: 'Beneficiary',
  BENEFICIARY_NAME: 'Beneficiary Name',
  BENEFICIARY_ZIP: 'Beneficiary Zip Code',
  BANK_ACCOUNT_INFORMATION: 'Bank Account information',
  BANK_NAME: 'Bank name ',
  ALAIS_TEXT: 'Alias',
  ACCOUNT_NUMBER: 'Account Number',
  ROUTING_ACH_ABA: 'Routing (ach aba)',
  ROUTING_WIRE_ABA: 'Routing (wire aba)',
  BANK_ADDRESS: 'Bank Address',
  SWIFT_BIC_CODE: 'Swift (bic code)',
  EURO_SEPA: 'EU/SEPA',
  IBAN_NUMBER: 'Iban Number',
  ACC_HOLDER_FULL_NAME: 'Full Name of Account Holder',
  EUR_ACC_NAME: 'Nombre de la empresa / organización benéfica',
  TYPE_EUR: 'EUR',
  TIRE: 'Tier',
  BASIC_INFO: 'Basic Information',
  ADITIONAL_INFO: 'Additional Information',
  BUSINESS_INFO: 'Business Information',
  REQUEST_CHANGES: 'Request Changes',
  SAVE_CHANGES: 'Save changes',
  CHANGE_PASSWORD: 'CHANGE PASSWORD',
  CURRENT_PASSWORD: 'CURRENT PASSWORD:',
  NEW_PASSWORD: 'NEW PASSWORD:',
  RETYPE_PASSWORD: 'RETYPE PASSWORD:',
  CHANGE_PASSWORD_LOWER: 'Change Password',
  SECURITY_OPTIONS: 'Security Options',
  RESET_LOGIN_2FA: 'Reset Login 2FA',
  EMAIL_AUTHENTICATION: 'E-MAIL AUTHENTICATION',
  EMAIL_SECURITY_CONTENT: 'Used For Withdrawal And Security Notifications',
  PRIMARY_GOOGLE_AUTH: 'GOOGLE 2FA AUTHENTICATION',
  SMS_AUTH: 'SMS AUTHENTICATION',
  SECONDARY_GOOGLE_AUTH: 'SECONDARY GOOGLE AUTHENTICATION',
  FACE_ID: 'FACE ID',
  TOUCH_ID: 'TOUCH ID',
  CONFIGURE_PASSCODE: 'CONFIGURE PASSCODE',
  SECONDARY_GOOGLE_AUTH_CONTENT: 'Used For Trading And Making Transactions',
  FACE_ID_CONTENT: 'Activate Face ID To Access To Your Account',
  TOUCH_ID_CONTENT: 'Activate Touch ID To Access To Your Account',
  PASSCODE_CONTENT:
    'If You Have Touch/Face ID Deactivated You Should Considerate To Add A Passcode',
  QRCODE_ISSUER: '&issuer=Mercury%20Cash&period=30',
  OTP_AUTH: 'otpauth://totp/',
  SECRET: '?secret=',
  PUSH_NOTIFICATION: 'PUSH NOTIFICATION',
  PUSH_CONTENT: 'Used For Trading And Making Transactions',
  TIME_LEFT_FOR_COMPLETING: 'Time Left for completing',
  THIS_TRANSACTION: '\nthis transaction ',
  CLOSE: 'Close',
  CONFIRM: 'Confirm',
  GOOGLE_AUTHENTICATOR: 'Google Authenticator',
  GOOGLE_AUTH_CONTENT: '1. Open Google Autenticator App\nand scan or copy your code',
  EMAIL_AUTHENTICATION_LOWER: 'E-mail Authentication',
  EMAIL_AUTHENTICATION_CONTENT:
    'Please take a moment to\ncheck your inbox and click on\nthe Approve Transaction Link.',
  DEPOSIT_AMOUNT: '?amount=',
  ACCOUNT_LIMITS: 'Acccount Limits',
  REQUEST_LIMIT_INCREASE: 'Request Limit Increase',
  BUY: 'Buy',
  CRYPTO_EXTERNAL_TRANSFER: 'Crypto External Transfer',
  FIAT_TRANSFER: 'Fiat Transfer',
  SELL: 'Sell',
  TRANSFER_EXTERNAL: 'Transfer External',
  TRANSFER_INTERNAL: 'Transfer Internal',
  PERCENT_USED: '% Used',
  PERCENT_LEFT: '% Left',
  SUPPORT_EMAIL: 'support@mercury.cash',
  INCREASE_LIMIT_MAIL_SUBJECT: 'Increase Limit Request',
  INCREASE_LIMIT_DESCRIPTION: 'Hi team \n \t\t I would like to increase my limit of my ',
  PROFILE_CHANGE_MAIL_SUBJECT: 'Change Profile Information - ',
  PROFILE_CHANGE_DESCRIPTION_1:
    'Hello, \n \t\t I would like to request a change of the following settings on my account. \n\n\n',
  PROFILE_CHANGE_DESCRIPTION_2: 'Please type the parameters you would like to change',
  PREFERED_LANG: 'Prefered Language',
  DEFAULT_CURRENCY: 'Default Currency',
  ENGLISH: 'English',
  SPANISH: 'Española',
  ESTONIAN: 'Eestlane',
  ENG: 'eng',
  EST: 'est',
  SPA: 'spa',
  DEPOSIT_LOWER: 'deposit',
  ACTIVATE: 'Activate',
  DELETE: 'Delete',
  EDIT_LABEL: 'Edit Label',
  VIEW_QR: 'View QR',
  LABEL_NAME: 'Label Name',
  CHANGE_NAME: 'Change Name',
  HIDE_QR: 'Hide QR',
  FIAT_WALLET_DESC_FIRST: 'Remember that your ',
  FIAT_WALLET_DESC_SECOND: ' is your e-mail address',
  SOURCE_BANK_ACCOUNT: 'Source Bank Account',
  SOURCE_BANK_FUNDS: 'Source Bank Funds',
  REQUIRED_FIELD: '* Required Field',
  LIMIT: 'Limit',
  FROM_FUND: 'From:',
  BANK_NAME_COLON: 'Bank Name:',
  COMPANY_NAME_COLON: 'Company Name:',
  ACCOUNT_NUMBER_COLON: 'Account Number:',
  BANK_ADDRESS_COLON: 'Bank Address:',
  ROUDING_ABA_COLON: 'Routing ABA:',
  SWIFT_COLON: 'Swift:',
  REFERENCE_CODE_COLON: 'Reference Code:',
  BANK_DETAILS: 'Bank Details',
  WIRE_TRANSFER_TITLE:
    'We have received your wire transfer\ndeposit request,\nplease be advised of the following:',
  PENALTY_DESC:
    'Use the reference code that you find above in\nyour transfer in order to better identify your\ntransaction, if you do not use the code you will\nbe charged with a ',
  PENALTY: ' penalty',
  SAVE_AS_PDF: 'Save As .PDF',
  RESET_PASSWORD: 'Reset Password',
  PROFESSIONAL_INFORMATION: 'Professional Information',
  PROFESSIONAL_INFO_DESC: 'Please enter your Professional information',
  TYPE_DOMESTIC: 1,
  TYPE_INTERNATIONAL: 2,
  TYPE_PERSONAL: 3,
  TYPE_BUSINESS: 4,
  TYPE_BANK_STATEMENT: 'bankStatement',
  TYPE_POA: 'poa',
  TYPE_ARTICLES: 'articles',
  TYPE_TAX_ID: 'taxId',
  TYPE_INCOMETAX: 'incomeTax',
  TYPE_DBA: 'dba',

  // array
  FUNDLIST_ITEMS: [
    {
      label: 'Investment',
      value: 'Investment',
    },
    {
      label: 'Income',
      value: 'Income',
    },
    {
      label: 'Business Activities',
      value: 'Business Activities',
    },
    {
      label: 'Other (Please Specify)',
      value: 'Other (Please Specify)',
    },
  ],
  WIRE_CODE: 'Wire Code',
  TOTAL: 'Total:',
  DATE_FORMATTOR: 'DD/MM/YYYY h:mm a ',
  FIAT_IN: 'fiatin',
  CRYPTO_IN: 'cryptoin',
  CRYPTO_IN_CAPS: 'cryptoIn',
  FIAT_OUT: 'fiatout',
  CRYPTO_OUT: 'cryptoout',
  CRYPTO_OUT_CAPS: 'cryptoOut',
  FIAT: 'fiat',
  FIAT_TRANSFER_TRANSACTIONS: 'fiatTransfer',
  CRYPTO: 'crypto',
  CRYPTO_TRANSFER_TRANSACTIONS: 'cryotoTransfer',
  PAGINATION_ITEMS: 10,
  // statements screen
  FILTER_BY: 'Filter by:',
  STATUS_ALL: 'All',
  STATUS_PENDING: 'Pending',
  STATUS_APPROVED: 'Approved',
  STATUS_REJECTED: 'Rejected',
  STATUS_REFUNDED: 'Refunded',
  INCLUDES_SECURITY: 'SECURITY',
  // Local Authendication
  FACEID: 'FaceID',
  TOUCHID: 'TouchID',
  NOT_AVAILABLE: 'is not available',
  AUTH_REQUIRED: 'Authentication Required',
  LOCAL_AUTHENDICATION:
    'Mercury cash required authendication to secure your account. \n\n Please unlock Mercury cash',
  UNLOCK_MERCURY: 'Unlock Mercury Cash',
}
